### ISSUE TITLE
Problem player Fos-Streaming ...

### ISSUE THREAD

**Issue by Guims** [zgelici/FOS-Streaming#6]
Hello,

I come to you because I have a problem with your script, I followed all the steps of facilities and also the steps updates the script, everything works fine, I can insert streaming links (.ts and .m3u8) but can not view the embedded player with the script.

do these extensions are supported by your script?

I use the VLC plugin for iceweasel, is it good?

Thank you for your script, and waiting for your reply I wish you a good day.

PS: I test your script with virtualbox and debian jessie.

**Comment by zgelici** [comment]
Hello Guims,

Soon i will be fix the play.php script.
Thanks for using this panel.

If there are any problems, you can submit a new issue.
 
Zadik
